apiVersion: v1
kind: Namespace
metadata:
  name: dirigible
---
apiVersion: v1
kind: Service
metadata:
  name: dirigible
  namespace: dirigible
  labels:
    app: dirigible
spec:
  ports:
  - port: 8080
    name: zeus
  clusterIP: None
  selector:
    app: dirigible
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zeus
  namespace: dirigible
spec:
  serviceName: "dirigible"
  replicas: 1
  template:
    metadata:
      labels:
        app: dirigible
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: dirigible
          image: dirigiblelabs/dirigible-tomcat:latest
          ports:
            - containerPort: 8080
              name: zeus
          volumeMounts:
            - name: root
              mountPath: /usr/local/tomcat/dirigible
          env:
            - name: localRepositoryRootFolder
              value: /usr/local/tomcat/dirigible/repository
            - name: localRepositoryRootFolderIsAbsolute
              value: "true"
            - name: localDatabaseRootFolder
              value: /usr/local/tomcat/dirigible/derby
            - name: localCmisRootFolder
              value: /usr/local/tomcat/dirigible/cmis
            - name: initLoggingDirectory
              value: /tomcat/logs
      serviceAccountName: dirigible
  volumeClaimTemplates:
    - metadata:
        name: root
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: dirigible
  namespace: dirigible
spec:
  rules:
    - host: dirigible.apps.eu-central-1.sap.onvms.com
      http:
        paths:
          - path: /
            backend:
              serviceName: dirigible
              servicePort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dirigible
  namespace: dirigible

---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: dirigible
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: dirigible
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dirigible
subjects:
  - kind: ServiceAccount
    name: dirigible
    namespace: dirigible
